#!/bin/sh
# AppRun: entrypoint invoked when the user double-clicks the AppImage.
# AppImage sets $APPDIR to the mounted filesystem's root.
HERE="$(dirname "$(readlink -f "$0")")"
exec "$HERE/usr/lib/jre/bin/java" \
    -jar "$HERE/usr/lib/breakthrough-gui.jar" \
    "$@"
